CREATE TABLE IF NOT EXISTS `#__discuss_thread` (
  `id` bigint(20) UNSIGNED NOT NULL auto_increment,
  `title` text NULL,
  `alias` text NOT NULL,
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified` datetime NULL DEFAULT '0000-00-00 00:00:00',
  `replied` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `user_id` bigint(20) UNSIGNED DEFAULT '0',
  `post_id` bigint(20) UNSIGNED DEFAULT '0',
  `user_type` varchar(255) NOT NULL,
  `poster_name` varchar(255) NOT NULL,
  `poster_email` varchar(255) NOT NULL,
  `last_user_id` bigint(20) UNSIGNED DEFAULT '0',
  `last_poster_name` varchar(255) NOT NULL,
  `last_poster_email` varchar(255) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `preview` LONGTEXT NULL,
  `published` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `category_id` bigint( 20 ) UNSIGNED NOT NULL DEFAULT 1,
  `ordering` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `vote` int(11) UNSIGNED DEFAULT '0',
  `sum_totalvote` int(11) NULL default 0,
  `hits` int(11) UNSIGNED DEFAULT '0',
  `islock` TINYINT(1) UNSIGNED DEFAULT '0',
  `lockdate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `featured` TINYINT(1) UNSIGNED DEFAULT '0',
  `isresolve` TINYINT(1) UNSIGNED DEFAULT '0',
  `isreport` TINYINT(1) UNSIGNED DEFAULT '0',
  `answered` TINYINT(1) UNSIGNED DEFAULT '0',
  `params` TEXT NOT NULL,
  `password` TEXT NULL,
  `legacy` tinyint(1) default 1,
  `address` TEXT NULL,
  `latitude` varchar(255) NOT NULL,
  `longitude` varchar(255) NOT NULL,
  `content_type` varchar(25) NULL,
  `post_status` tinyint(1) NOT NULL DEFAULT 0,
  `post_type` varchar(255) NOT NULL DEFAULT 0,
  `private` tinyint(3) NOT NULL DEFAULT 0,
  `num_likes` int(11) NULL default 0,
  `num_replies` int(11) NULL default 0,
  `num_negvote` int(11) NULL default 0,
  `num_fav` int(11) NULL default 0,
  `num_attachments` int(11) NULL default 0,
  `has_polls` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `cluster_id` int(11) NULL default 0,
  `cluster_type` varchar(255) NULL default 0,
  PRIMARY KEY  (`id`),
  KEY `idx_postid` (`post_id`),
  KEY `idx_published` (`published`),
  KEY `idx_userid` (`user_id`) ,
  KEY `idx_vote` (`vote`),
  KEY `idx_isreport` (`isreport`),
  KEY `idx_answered` (`answered`),
  KEY `idx_category` (`category_id`),
  KEY `unread_category_posts` (`published`,`legacy`, `category_id`, `id` ),
  FULLTEXT `discuss_post_titlecontent` (`title`, `content`),
  KEY `idx_post_type` ( `post_type` ),
  KEY `idx_post_replied` (`replied`),
  KEY `idx_post_created` (`created`),
  KEY `idx_post_search1` (`published`, `private`),
  KEY `idx_post_search2` (`published`, `private`, `replied`),
  KEY `idx_post_search3` (`published`, `private`, `created`),
  KEY `idx_user_replies` (`user_id`, `published`),
  KEY `idx_post_cat_published` (`category_id`, `published`),
  KEY `idx_featured` (`published`, `featured`, `private`, `cluster_id`, `replied`),
  KEY `idx_forums_featured_replied` (`published`, `private`, `cluster_id`, `category_id`, `featured`, `replied`),
  KEY `idx_forums` (`published`, `private`, `cluster_id`, `category_id`),
  KEY `idx_feature` (`featured`),
  KEY `idx_replied` (`replied`),
  KEY `idx_isresolve` (`isresolve`),
  KEY `idx_resolved_thread` (`published`, `isresolve`),
  KEY `idx_unanswered_count` (`published`, `isresolve`, `num_replies`, `cluster_id`, `category_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__discuss_posts` (
  `id` bigint(20) UNSIGNED NOT NULL auto_increment,
  `title` text NULL,
  `alias` text NOT NULL,
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified` datetime NULL DEFAULT '0000-00-00 00:00:00',
  `replied` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `content` longtext NOT NULL,
  `preview` longtext NULL,
  `published` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `ordering` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `vote` int(11) UNSIGNED DEFAULT '0',
  `hits` int(11) UNSIGNED DEFAULT '0',
  `ip` VARCHAR(255) NOT NULL,
  `islock` TINYINT(1) UNSIGNED DEFAULT '0',
  `lockdate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `featured` TINYINT(1) UNSIGNED DEFAULT '0',
  `isresolve` TINYINT(1) UNSIGNED DEFAULT '0',
  `isreport` TINYINT(1) UNSIGNED DEFAULT '0',
  `answered` TINYINT(1) UNSIGNED DEFAULT '0',
  `user_id` bigint(20) UNSIGNED DEFAULT '0',
  `parent_id` bigint(20) UNSIGNED DEFAULT '0',
  `user_type` varchar(255) NOT NULL,
  `poster_name` varchar(255) NOT NULL,
  `poster_email` varchar(255) NOT NULL,
  `num_likes` int(11) NULL default 0,
  `num_negvote` int(11) NULL default 0,
  `num_fav` int(11) NULL default 0,
  `sum_totalvote` int(11) NULL default 0,
  `category_id` bigint( 20 ) UNSIGNED NOT NULL DEFAULT 1,
  `params` TEXT NOT NULL,
  `password` TEXT NULL,
  `legacy` tinyint(1) default 1,
  `address` TEXT NULL,
  `latitude` varchar(255) NOT NULL,
  `longitude` varchar(255) NOT NULL,
  `content_type` varchar(25) NULL,
  `post_status` tinyint(1) NOT NULL DEFAULT 0,
  `post_type` varchar(255) NOT NULL DEFAULT 0,
  `private` tinyint(3) NOT NULL DEFAULT 0,
  `thread_id` bigint(20) UNSIGNED DEFAULT 0,
  `priority` INT(11) NULL,
  `anonymous` tinyint(3) NULL default 0,
  `cluster_id` int(11) NULL default 0,
  `cluster_type` varchar(255) NULL default 0,
  PRIMARY KEY  (`id`),
  KEY `discuss_post_published` (`published`),
  KEY `discuss_post_user_id` (`user_id`) ,
  KEY `discuss_post_vote` (`vote`),
  KEY `discuss_post_parentid` (`published`, `parent_id`),
  KEY `discuss_post_isreport` (`isreport`),
  KEY `discuss_post_answered` (`answered`),
  KEY `discuss_post_category` (`category_id`),
  KEY `discuss_post_query1` (`published`, `parent_id`, `answered`, `id`),
  KEY `discuss_post_query2` (`published`, `parent_id`, `answered`, `replied`),
  KEY `discuss_post_query3` (`published`, `parent_id`, `category_id`, `created`),
  KEY `discuss_post_query4` (`published`, `parent_id`, `category_id`, `id`),
  KEY `discuss_post_query5` (`published`, `parent_id`, `created`),
  KEY `discuss_post_query6` (`published`, `parent_id`, `id`),
  KEY `unread_category_posts` (`published`, `parent_id`, `legacy`, `category_id`, `id` ),
  FULLTEXT `discuss_post_titlecontent` (`title`, `content`),
  KEY `discuss_post_last_reply` ( `parent_id`, `id` ),
  KEY `idx_post_type` ( `post_type` ),
  KEY `idx_post_replied` (`replied`),
  KEY `idx_post_created` (`created`),
  KEY `idx_post_private` (`private`),
  KEY `idx_post_search1` (`published`, `parent_id`, `private`, `replied`),
  KEY `idx_post_search2` (`published`, `private`, `created`),
  KEY `idx_post_search1a` (`published`, `parent_id`, `private`),
  KEY `idx_post_search2a` (`published`, `private`),
  KEY `idx_user_replies` (`user_id`, `published`, `parent_id`),
  KEY `idx_post_cat_published` (`category_id`, `published`),
  KEY `idx_threadid` (`thread_id`),
  KEY `idx_post_replies` (`published`, `parent_id`, `answered`, `created`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `#__discuss_posts_references` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `post_id` bigint(20) NOT NULL,
  `reference_id` bigint(20) NOT NULL,
  `extension` text NOT NULL,
  PRIMARY KEY (`id`),
  KEY `post_id` (`post_id`,`reference_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__discuss_post_types` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar( 255 ) NOT NULL,
  `suffix` varchar(50) NOT NULL,
  `created` datetime NOT NULL,
  `published` tinyint(3) NOT NULL,
  `alias` varchar( 255 ) NOT NULL,
  `type` varchar(255) NOT NULL DEFAULT 'global',
  `lft` int(11) NULL,
  `rgt` int(11) NULL,
  PRIMARY KEY (`id`),
  KEY `idx_alias` (`alias`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `#__discuss_post_types_category` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_association` (`type_id`, `category_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__discuss_attachments` (
  `id` int(11) NOT NULL auto_increment,
  `uid` int(11) NOT NULL,
  `title` text NOT NULL,
  `type` varchar(200) NOT NULL,
  `path` text NOT NULL,
  `created` datetime NOT NULL,
  `published` tinyint(3) NOT NULL,
  `mime` text NOT NULL,
  `size` text NOT NULL,
  `storage` VARCHAR(255) NOT NULL DEFAULT 'joomla',
  PRIMARY KEY  (`id`),
  KEY `uid` (`uid`),
  KEY `type` (`type`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS `#__discuss_attachments_tmp` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `path` text NOT NULL,
  `title` text NOT NULL,
  `mime` varchar(255) NOT NULL,
  `size` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `userid` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__discuss_priorities` (
  `id` int(11) NOT NULL auto_increment,
  `title` varchar(255) NOT NULL,
  `color` varchar(255) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
